"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.dlsiteTagMap = void 0;
exports.resolveTagName = resolveTagName;
function resolveTagName(tagId, tagLanguage) {
    const entry = exports.dlsiteTagMap[tagId];
    if (!entry)
        return undefined;
    if (entry[tagLanguage])
        return entry[tagLanguage];
    const prefix = tagLanguage.split('-')[0];
    const prefixMatch = Object.keys(entry).find((locale) => locale.startsWith(prefix + '-'));
    if (prefixMatch)
        return entry[prefixMatch];
    return entry['ja-jp'];
}
exports.dlsiteTagMap = {
    1: { 'en-us': 'School / Academy', 'ja-jp': '学校/学園', 'zh-cn': '学校/学园', 'zh-tw': '學校/校園' },
    2: { 'en-us': 'Office / Workplace', 'ja-jp': 'オフィス/職場', 'zh-cn': '办公室/职场', 'zh-tw': '辦公室/職場' },
    3: { 'en-us': 'Outdoor', 'ja-jp': '屋外', 'zh-cn': '室外', 'zh-tw': '戶外' },
    4: { 'en-us': 'Lovey Dovey / Sweet Love', 'ja-jp': 'ラブラブ/あまあま', 'zh-cn': '纯爱/甜蜜', 'zh-tw': '恩愛' },
    5: { 'en-us': 'Gag / Joke', 'ja-jp': 'ギャグ', 'zh-cn': '搞笑', 'zh-tw': '搞笑' },
    6: { 'en-us': 'Decadent / Immoral', 'ja-jp': '退廃/背徳/インモラル', 'zh-cn': '颓废/背德', 'zh-tw': '頹廢/背德' },
    7: { 'en-us': 'Comedy', 'ja-jp': 'コメディ', 'zh-cn': '喜剧', 'zh-tw': '喜劇' },
    8: { 'en-us': 'Slice of Life / Daily Living', 'ja-jp': '日常/生活', 'zh-cn': '日常/生活', 'zh-tw': '日常/生活' },
    9: { 'en-us': 'Military', 'ja-jp': 'ミリタリー', 'zh-cn': '军事', 'zh-tw': '軍武' },
    10: { 'en-us': 'SF', 'ja-jp': 'SF', 'zh-cn': '科幻', 'zh-tw': '科幻' },
    11: { 'en-us': 'Sports', 'ja-jp': 'スポーツ', 'zh-cn': '运动', 'zh-tw': '運動' },
    12: { 'en-us': 'Fighting / Martial Arts', 'ja-jp': '格闘', 'zh-cn': '格斗', 'zh-tw': '格鬥' },
    13: { 'en-us': 'Heartwarming', 'ja-jp': 'ほのぼの', 'zh-cn': '温馨', 'zh-tw': '溫馨' },
    14: { 'en-us': 'Lovers', 'ja-jp': '恋人同士', 'zh-cn': '情侣', 'zh-tw': '情侶/戀人' },
    15: { 'en-us': 'Serious', 'ja-jp': 'シリアス', 'zh-cn': '严肃', 'zh-tw': '嚴肅' },
    16: { 'en-us': 'Fantasy', 'ja-jp': 'ファンタジー', 'zh-cn': '幻想', 'zh-tw': '幻想' },
    17: { 'en-us': 'Epic / Historical', 'ja-jp': '歴史/時代物', 'zh-cn': '历史/时代物', 'zh-tw': '歷史/古裝題材' },
    19: { 'en-us': 'Horror', 'ja-jp': 'ホラー', 'zh-cn': '恐怖', 'zh-tw': '恐怖' },
    20: { 'en-us': 'Cat Fight', 'ja-jp': 'キャットファイト', 'zh-cn': '女子互斗', 'zh-tw': '女性格鬥' },
    22: { 'en-us': 'Suspense', 'ja-jp': 'サスペンス', 'zh-cn': '悬疑', 'zh-tw': '懸疑' },
    24: { 'en-us': 'Violence', 'ja-jp': 'バイオレンス', 'zh-cn': '暴力', 'zh-tw': '暴力' },
    25: { 'ja-jp': 'ヤキモチ' },
    26: { 'en-us': 'Occult', 'ja-jp': 'オカルト', 'zh-cn': '神秘现象', 'zh-tw': '超自然現象' },
    27: { 'en-us': 'Teens Love', 'zh-cn': 'Teens love', 'zh-tw': 'Teens love' },
    28: { 'en-us': 'Age Disparity', 'ja-jp': '歳の差', 'zh-cn': '年龄差', 'zh-tw': '年齡差異' },
    29: { 'en-us': 'Magic', 'ja-jp': '魔法', 'zh-cn': '魔法', 'zh-tw': '魔法' },
    30: { 'ja-jp': '芸能' },
    31: { 'en-us': 'Living Together', 'ja-jp': '同居', 'zh-cn': '同居', 'zh-tw': '同居' },
    32: { 'en-us': 'Pure Love', 'ja-jp': '純愛', 'zh-cn': '纯爱', 'zh-tw': '純愛' },
    33: { 'en-us': 'Ephebophilia / Shonen-ai', 'ja-jp': '耽美', 'zh-cn': '耽美', 'zh-tw': '耽美' },
    34: { 'en-us': 'War / Battlefield', 'ja-jp': '戦場', 'zh-cn': '战场', 'zh-tw': '戰場' },
    35: { 'en-us': 'Peeing Oneself', 'ja-jp': 'おもらし', 'zh-cn': '失禁', 'zh-tw': '失禁' },
    37: { 'en-us': 'Boys Love', 'zh-cn': 'BL/男同性恋', 'zh-tw': 'BL' },
    39: { 'ja-jp': '年下攻' },
    40: { 'en-us': 'Aggressive (Submissive)', 'ja-jp': '襲い受', 'zh-cn': '侵犯受' },
    42: { 'en-us': 'Totally (Dominant)', 'ja-jp': '総攻', 'zh-cn': '总攻' },
    43: { 'en-us': 'Strong Willed (Dominant)', 'ja-jp': '強気攻', 'zh-cn': '强气攻' },
    44: { 'en-us': 'Totally (Submissive)', 'ja-jp': '総受', 'zh-cn': '总受' },
    46: { 'en-us': 'Harem', 'ja-jp': 'ハーレム', 'zh-cn': '后宫', 'zh-tw': '後宮' },
    47: { 'en-us': 'Yaoi', 'ja-jp': 'やおい', 'zh-cn': '男同性恋', 'zh-tw': 'YAOI' },
    48: { 'en-us': 'Cuckoldry (Netorare)', 'ja-jp': '寝取られ', 'zh-cn': '被NTR(苦主视角)', 'zh-tw': 'NTR' },
    49: { 'en-us': 'Clothed', 'ja-jp': '着衣', 'zh-cn': '着衣/穿衣', 'zh-tw': '著衣' },
    50: { 'en-us': 'Chirarism (Peeping)', 'ja-jp': 'チラリズム', 'zh-cn': '走光', 'zh-tw': '走光' },
    51: { 'en-us': 'Moe', 'ja-jp': '萌え', 'zh-cn': '萌', 'zh-tw': '萌' },
    52: { 'en-us': 'Hot / Burning', 'ja-jp': '燃え', 'zh-cn': '燃', 'zh-tw': '燃' },
    53: { 'en-us': 'Wholesome', 'ja-jp': '健全', 'zh-cn': '健全' },
    54: { 'ja-jp': 'ベタ/コテコテ' },
    55: { 'en-us': 'Emotional / Touching', 'ja-jp': '感動', 'zh-cn': '感动', 'zh-tw': '感動' },
    56: { 'en-us': 'Healing', 'ja-jp': '癒し', 'zh-cn': '治愈', 'zh-tw': '療癒' },
    57: { 'en-us': 'Plain / Nonpersisting', 'ja-jp': '淡白/あっさり', 'zh-cn': '平淡/轻松', 'zh-tw': '平淡/輕鬆' },
    58: { 'en-us': 'Totally Happy', 'ja-jp': 'オールハッピー', 'zh-cn': '皆大欢喜', 'zh-tw': '皆大歡喜' },
    59: { 'en-us': 'Tsundere', 'ja-jp': 'ツンデレ', 'zh-cn': '傲娇', 'zh-tw': '傲嬌' },
    60: { 'en-us': 'Woman\'s Viewpoint', 'ja-jp': '女性視点', 'zh-cn': '女性视角', 'zh-tw': '女性角度' },
    61: { 'en-us': 'Depression / Depressing', 'ja-jp': '鬱', 'zh-cn': '抑郁', 'zh-tw': '憂鬱' },
    62: { 'en-us': 'Legs', 'ja-jp': '脚', 'zh-cn': '足/脚', 'zh-tw': '足/腳' },
    63: { 'en-us': 'Buttocks', 'ja-jp': 'お尻/ヒップ', 'zh-cn': '臀部/屁股', 'zh-tw': '屁股/臀部' },
    64: { 'en-us': 'Fetish', 'ja-jp': 'フェチ', 'zh-cn': '癖好/性趣', 'zh-tw': '性癖好' },
    65: { 'en-us': 'Breasts', 'ja-jp': 'おっぱい', 'zh-cn': '胸部/奶子', 'zh-tw': '胸部/奶子' },
    66: { 'en-us': 'Abnormal / Perverted', 'ja-jp': 'マニアック/変態', 'zh-cn': '特殊癖好/变态', 'zh-tw': '特殊癖好/變態' },
    67: { 'ja-jp': 'アブノーマル' },
    68: { 'en-us': 'Dirty Talk', 'ja-jp': '淫語', 'zh-cn': '淫语', 'zh-tw': '淫語' },
    69: { 'en-us': 'Lots of White Cream / Juices', 'ja-jp': '汁/液大量', 'zh-cn': '大量汁/液', 'zh-tw': '大量液體' },
    70: { 'en-us': 'Successive Orgasms', 'ja-jp': '連続絶頂', 'zh-cn': '连续高潮', 'zh-tw': '連續高潮' },
    71: { 'en-us': 'Cross-section View', 'ja-jp': '断面図', 'zh-cn': '断面图', 'zh-tw': '剖面圖' },
    73: { 'en-us': 'Anime', 'ja-jp': 'アニメ', 'zh-cn': '动画', 'zh-tw': '動畫' },
    74: { 'en-us': 'Uniform', 'ja-jp': '制服', 'zh-cn': '制服', 'zh-tw': '制服' },
    75: { 'en-us': 'Sailor-style Uniform', 'ja-jp': 'セーラー服', 'zh-cn': '水手服', 'zh-tw': '水手服' },
    76: { 'en-us': 'PE Uniform', 'ja-jp': '体操着', 'zh-cn': '体操服', 'zh-tw': '體操服' },
    77: { 'en-us': 'Swimwear', 'ja-jp': '水着', 'zh-cn': '泳衣', 'zh-tw': '泳衣' },
    78: { 'en-us': 'Maid', 'ja-jp': 'メイド', 'zh-cn': '女仆', 'zh-tw': '女僕' },
    79: { 'en-us': 'Nurse', 'ja-jp': 'ナース', 'zh-cn': '护士', 'zh-tw': '護士' },
    80: { 'en-us': 'Shrine Maiden', 'ja-jp': '巫女', 'zh-cn': '巫女', 'zh-tw': '巫女' },
    81: { 'en-us': 'Army Uniform', 'ja-jp': '軍服', 'zh-cn': '军服', 'zh-tw': '軍服' },
    82: { 'en-us': 'Underwear', 'ja-jp': '下着', 'zh-cn': '内衣', 'zh-tw': '內衣' },
    83: { 'en-us': 'Panties', 'ja-jp': 'パンツ', 'zh-cn': '内裤', 'zh-tw': '內褲' },
    85: { 'en-us': 'Gothic Lolita', 'ja-jp': 'ゴスロリ', 'zh-cn': '哥特萝莉', 'zh-tw': '哥德蘿莉' },
    86: { 'en-us': 'Cosplay', 'ja-jp': 'コスプレ', 'zh-cn': 'cosplay/角色扮演', 'zh-tw': 'cosplay/角色扮演' },
    87: { 'en-us': 'Bondage', 'ja-jp': 'ボンデージ', 'zh-cn': '拘束服', 'zh-tw': '拘束服' },
    88: { 'en-us': 'Bloomers / Buruma', 'ja-jp': 'ブルマ', 'zh-cn': '校园体操服', 'zh-tw': '運動短褲' },
    90: { 'en-us': 'Short Skirt', 'ja-jp': 'ミニスカ', 'zh-cn': '迷你裙', 'zh-tw': '迷你裙' },
    91: { 'en-us': 'Kimono / Japanese Clothes', 'ja-jp': '着物/和服', 'zh-cn': '和服', 'zh-tw': '和服' },
    92: { 'en-us': 'Apron', 'ja-jp': 'エプロン', 'zh-cn': '围裙', 'zh-tw': '圍裙' },
    93: { 'en-us': 'Rubber', 'ja-jp': 'ラバー', 'zh-cn': '胶衣', 'zh-tw': '皮衣' },
    94: { 'en-us': 'Leotard', 'ja-jp': 'レオタード', 'zh-cn': '紧身衣', 'zh-tw': '緊身衣' },
    96: { 'en-us': 'Sister / Nun', 'ja-jp': 'シスター', 'zh-cn': '修女', 'zh-tw': '修女' },
    98: { 'en-us': 'Waitress', 'ja-jp': 'ウェイトレス', 'zh-cn': '侍女', 'zh-tw': '女服務生' },
    99: { 'en-us': 'Bunny Girl', 'ja-jp': 'バニーガール', 'zh-cn': '兔女郎', 'zh-tw': '兔女郎' },
    100: { 'en-us': 'Leggings', 'ja-jp': 'スパッツ', 'zh-cn': '紧身裤', 'zh-tw': '緊身褲' },
    101: { 'en-us': 'Knee Socks', 'ja-jp': 'ニーソックス', 'zh-cn': '过膝袜', 'zh-tw': '過膝襪' },
    102: { 'en-us': 'Stockings', 'ja-jp': 'ストッキング', 'zh-cn': '丝袜', 'zh-tw': '絲襪/褲襪' },
    104: { 'en-us': 'School Swimwear', 'ja-jp': 'スクール水着', 'zh-cn': '校园泳衣', 'zh-tw': '學校泳衣' },
    105: { 'en-us': 'Suit', 'ja-jp': 'スーツ', 'zh-cn': '西服', 'zh-tw': '西裝' },
    107: { 'en-us': 'Garter', 'ja-jp': 'ガーター', 'zh-cn': '袜带', 'zh-tw': '襪帶' },
    111: { 'en-us': 'Cross-dressing as a Woman', 'ja-jp': '女装', 'zh-cn': '女装', 'zh-tw': '女裝' },
    112: { 'en-us': 'Vanilla Sex', 'ja-jp': 'ノーマルプレイ', 'zh-cn': '正常玩法', 'zh-tw': '正常性愛' },
    113: { 'en-us': 'Rape', 'ja-jp': 'レイプ', 'zh-cn': '强奸' },
    114: { 'en-us': 'Coercion / Compulsion', 'ja-jp': '強制/無理矢理', 'zh-cn': '强制/硬上' },
    115: { 'en-us': 'Reverse Rape', 'ja-jp': '逆レイプ', 'zh-cn': '逆强奸/女上男' },
    116: { 'en-us': 'Orgy Sex', 'ja-jp': '複数プレイ/乱交', 'zh-cn': '多p/乱交', 'zh-tw': '多P' },
    117: { 'en-us': 'Erotic Sexual Denial', 'ja-jp': '放置プレイ', 'zh-cn': '放置play', 'zh-tw': '放置play' },
    118: { 'en-us': 'Lesbian', 'ja-jp': 'レズ/女同士', 'zh-cn': '蕾丝/女同', 'zh-tw': '蕾絲/女同' },
    119: { 'en-us': 'Male Homosexuality', 'ja-jp': 'ゲイ/男同士', 'zh-cn': 'GAY/男同', 'zh-tw': '男同性戀' },
    120: { 'en-us': 'Incest', 'ja-jp': '近親相姦', 'zh-cn': '近亲相奸' },
    121: { 'en-us': 'Gangbang', 'ja-jp': '輪姦', 'zh-cn': '轮奸' },
    122: { 'en-us': 'Breast Sex', 'ja-jp': 'パイズリ', 'zh-cn': '乳交', 'zh-tw': '乳交' },
    123: { 'en-us': 'Consensual Sex', 'ja-jp': '和姦', 'zh-cn': '通奸', 'zh-tw': '通姦' },
    124: { 'en-us': 'Hand Job', 'ja-jp': '手コキ', 'zh-cn': '手交', 'zh-tw': '打手槍/手交' },
    125: { 'en-us': 'Foot Job', 'ja-jp': '足コキ', 'zh-cn': '足交', 'zh-tw': '足交' },
    126: { 'en-us': 'Bukkake', 'ja-jp': 'ぶっかけ', 'zh-cn': '外射', 'zh-tw': '外射' },
    127: { 'en-us': 'Facial Cumshot', 'ja-jp': '顔射', 'zh-cn': '颜射', 'zh-tw': '顏射' },
    128: { 'en-us': 'Internal Cumshot', 'ja-jp': '中出し', 'zh-cn': '内射/中出', 'zh-tw': '內射/中出' },
    129: { 'en-us': 'Pregnancy / Impregnation', 'ja-jp': '妊娠/孕ませ', 'zh-cn': '怀孕', 'zh-tw': '懷孕' },
    130: { 'en-us': 'Breast Milk', 'ja-jp': '母乳', 'zh-cn': '母乳', 'zh-tw': '母乳' },
    131: { 'en-us': 'Milking', 'ja-jp': '搾乳', 'zh-cn': '榨乳', 'zh-tw': '榨乳' },
    132: { 'en-us': 'Childbirth', 'ja-jp': '出産', 'zh-cn': '出产', 'zh-tw': '生產' },
    133: { 'en-us': 'Egg Laying', 'ja-jp': '産卵', 'zh-cn': '产卵', 'zh-tw': '產卵' },
    134: { 'en-us': 'Violation', 'ja-jp': '陵辱', 'zh-cn': '凌辱' },
    135: { 'en-us': 'Masturbation', 'ja-jp': 'オナニー', 'zh-cn': '自慰', 'zh-tw': '自慰' },
    136: { 'en-us': 'SM', 'ja-jp': 'SM', 'zh-cn': 'SM', 'zh-tw': 'SM' },
    137: { 'en-us': 'Sexual Bondage', 'ja-jp': '緊縛', 'zh-cn': '捆绑/紧缚', 'zh-tw': '捆綁/緊縛' },
    138: { 'en-us': 'Blowjob / Fellatio', 'ja-jp': 'フェラチオ', 'zh-cn': '口交', 'zh-tw': '口交' },
    139: { 'en-us': 'Molestation', 'ja-jp': '痴漢', 'zh-cn': '痴汉' },
    140: { 'en-us': 'Sexual Training', 'ja-jp': '調教', 'zh-cn': '调教' },
    141: { 'ja-jp': '変態' },
    142: { 'en-us': 'Naughty / Lewd', 'ja-jp': '淫乱', 'zh-cn': '淫乱', 'zh-tw': '淫亂' },
    143: { 'en-us': 'Outdoor Exposure', 'ja-jp': '露出', 'zh-cn': '露出', 'zh-tw': '露出' },
    144: { 'en-us': 'Verbal Humiliation', 'ja-jp': '言葉責め', 'zh-cn': '言语侵犯', 'zh-tw': '言語羞辱' },
    145: { 'en-us': 'Outdoor Sex', 'ja-jp': '青姦', 'zh-cn': '野战', 'zh-tw': '野戰' },
    146: { 'en-us': 'Restraint', 'ja-jp': '拘束', 'zh-cn': '拘束', 'zh-tw': '拘束' },
    147: { 'en-us': 'Slave', 'ja-jp': '奴隷', 'zh-cn': '奴隶' },
    148: { 'en-us': 'Enema', 'ja-jp': '浣腸', 'zh-cn': '灌肠', 'zh-tw': '灌腸' },
    149: { 'en-us': 'Shame / Humiliation', 'ja-jp': '羞恥/恥辱', 'zh-cn': '羞耻/耻辱', 'zh-tw': '羞恥/恥辱' },
    150: { 'ja-jp': '恥辱' },
    151: { 'en-us': 'Captivity', 'ja-jp': '監禁', 'zh-cn': '监禁' },
    152: { 'en-us': 'Tease', 'ja-jp': '焦らし', 'zh-cn': '焦躁', 'zh-tw': '使其焦急' },
    153: { 'en-us': 'Tickling', 'ja-jp': 'くすぐり', 'zh-cn': '瘙痒', 'zh-tw': '搔癢' },
    154: { 'en-us': 'Fiendish / Brutal', 'ja-jp': '鬼畜', 'zh-cn': '鬼畜' },
    155: { 'en-us': 'Upskirt / Spy Photo', 'ja-jp': '盗撮', 'zh-cn': '偷拍/盗摄', 'zh-tw': '偷拍/盜攝' },
    156: { 'en-us': 'Submissive Man', 'ja-jp': '男性受け', 'zh-cn': '男性受', 'zh-tw': '男性受' },
    157: { 'en-us': 'Hypnosis', 'ja-jp': '催眠', 'zh-cn': '催眠' },
    158: { 'en-us': 'Yuri / Girls Love', 'ja-jp': '百合', 'zh-cn': '百合', 'zh-tw': '百合' },
    159: { 'en-us': 'Urination / Peeing', 'ja-jp': '放尿/おしっこ', 'zh-cn': '放尿', 'zh-tw': '放尿/小便' },
    160: { 'en-us': 'Anal', 'ja-jp': 'アナル', 'zh-cn': '肛交', 'zh-tw': '肛交' },
    161: { 'en-us': 'Scatology', 'ja-jp': 'スカトロ', 'zh-cn': '粪尿', 'zh-tw': '糞尿' },
    162: { 'en-us': 'Tentacle', 'ja-jp': '触手', 'zh-cn': '触手', 'zh-tw': '觸手' },
    163: { 'en-us': 'Bestiality', 'ja-jp': '獣姦', 'zh-cn': '兽奸' },
    164: { 'en-us': 'Machine Sex', 'ja-jp': '機械姦', 'zh-cn': '机械奸' },
    165: { 'en-us': 'Stretch / Expansion', 'ja-jp': '拡張', 'zh-cn': '扩张', 'zh-tw': '擴張' },
    166: { 'en-us': 'Short Hair', 'ja-jp': 'ショートカット', 'zh-cn': '短发', 'zh-tw': '短髮' },
    167: { 'en-us': 'Long Hair', 'ja-jp': 'ロングヘア', 'zh-cn': '长发', 'zh-tw': '長髮' },
    170: { 'en-us': 'Blonde Hair', 'ja-jp': '金髪', 'zh-cn': '金发', 'zh-tw': '金髮' },
    171: { 'en-us': 'Black Hair', 'ja-jp': '黒髪', 'zh-cn': '黑发', 'zh-tw': '黑髮' },
    173: { 'en-us': 'Ponytail', 'ja-jp': 'ポニーテール', 'zh-cn': '马尾辫', 'zh-tw': '馬尾' },
    174: { 'en-us': 'Twin Tail', 'ja-jp': 'ツインテール', 'zh-cn': '双马尾', 'zh-tw': '雙馬尾' },
    175: { 'en-us': 'Nekomimi (Cat Ears)', 'ja-jp': 'ネコミミ', 'zh-cn': '猫耳', 'zh-tw': '貓耳' },
    176: { 'en-us': 'Animal Ears', 'ja-jp': '獣耳', 'zh-cn': '兽耳', 'zh-tw': '獸耳' },
    177: { 'en-us': 'Tall Person', 'ja-jp': '長身', 'zh-cn': '长身', 'zh-tw': '高挑身材' },
    178: { 'en-us': 'Slender', 'ja-jp': 'スレンダー', 'zh-cn': '苗条', 'zh-tw': '苗條' },
    179: { 'en-us': 'Voluptuous / Plump', 'ja-jp': 'ムチムチ', 'zh-cn': '丰满', 'zh-tw': '豐滿' },
    180: { 'ja-jp': '羽根' },
    181: { 'en-us': 'Muscular', 'ja-jp': '筋肉', 'zh-cn': '肌肉', 'zh-tw': '肌肉' },
    182: { 'en-us': 'Big Breasts', 'ja-jp': '巨乳/爆乳', 'zh-cn': '巨乳/爆乳', 'zh-tw': '巨乳/爆乳' },
    183: { 'en-us': 'Tiny Breasts', 'ja-jp': '貧乳/微乳', 'zh-cn': '贫乳/微乳', 'zh-tw': '貧乳/微乳' },
    184: { 'en-us': 'Multi / Monster / Mega Breasts', 'ja-jp': '複乳/怪乳/超乳', 'zh-cn': '复乳/怪乳/超乳', 'zh-tw': '復乳/怪乳/超乳' },
    185: { 'en-us': 'Nipples / Areola', 'ja-jp': '乳首/乳輪', 'zh-cn': '乳头/乳晕', 'zh-tw': '乳頭/乳暈' },
    186: { 'en-us': 'Pregnant Woman', 'ja-jp': 'ぼて腹/妊婦', 'zh-cn': '西瓜肚/孕妇', 'zh-tw': '大肚子/孕婦' },
    187: { 'en-us': 'Tsurupeta', 'ja-jp': 'ツルペタ', 'zh-cn': '飞机场/平胸', 'zh-tw': '洗衣板/飛機場' },
    188: { 'en-us': 'No Pubic Hair', 'ja-jp': 'パイパン', 'zh-cn': '白虎/无阴毛', 'zh-tw': '白虎/無陰毛' },
    189: { 'en-us': 'Pubic Hair / Armpit Hair', 'ja-jp': '陰毛/腋毛', 'zh-cn': '阴毛/腋毛', 'zh-tw': '陰毛/腋毛' },
    190: { 'en-us': 'Futanari / Hermaphrodite', 'ja-jp': 'フタナリ', 'zh-cn': '扶她', 'zh-tw': '扶他' },
    191: { 'en-us': 'Large Cock', 'ja-jp': '巨根', 'zh-cn': '巨根', 'zh-tw': '巨根' },
    192: { 'en-us': 'Virgin Male', 'ja-jp': '童貞', 'zh-cn': '童贞', 'zh-tw': '處男/童貞' },
    193: { 'en-us': 'Virgin Female', 'ja-jp': '処女', 'zh-cn': '处女', 'zh-tw': '處女' },
    194: { 'en-us': 'Supersize', 'ja-jp': '巨大化', 'zh-cn': '巨大化', 'zh-tw': '巨大化' },
    195: { 'ja-jp': 'しっぽ' },
    196: { 'en-us': 'Dialect (Language)', 'ja-jp': '方言', 'zh-cn': '方言', 'zh-tw': '方言' },
    197: { 'en-us': 'Boyish Girl', 'ja-jp': 'ボクっ娘', 'zh-cn': '男性自称少女/僕娘', 'zh-tw': '男性自稱少女/僕娘' },
    198: { 'en-us': 'Expressionless / Deadpan', 'ja-jp': '無表情', 'zh-cn': '无表情', 'zh-tw': '無表情' },
    199: { 'en-us': 'Bizarre / Eccentric', 'ja-jp': '猟奇', 'zh-cn': '猎奇', 'zh-tw': '獵奇' },
    200: { 'en-us': 'Body Modification', 'ja-jp': '人体改造', 'zh-cn': '人体改造', 'zh-tw': '人體改造' },
    201: { 'en-us': 'Torture', 'ja-jp': '拷問', 'zh-cn': '拷问' },
    202: { 'en-us': 'Fisting / Fist Sex', 'ja-jp': 'フィストファック', 'zh-cn': '拳交', 'zh-tw': '拳交' },
    203: { 'en-us': 'Nipple Penetration', 'ja-jp': 'ニプルファック', 'zh-cn': '乳头交', 'zh-tw': '乳頭交' },
    204: { 'en-us': 'Blood / Bleeding', 'ja-jp': '血液/流血', 'zh-cn': '血液/流血', 'zh-tw': '血液/流血' },
    205: { 'en-us': 'Madness', 'ja-jp': '狂気', 'zh-cn': '狂气', 'zh-tw': '狂氣' },
    206: { 'en-us': 'Girl', 'ja-jp': '少女', 'zh-cn': '少女', 'zh-tw': '少女' },
    207: { 'en-us': 'Loli', 'ja-jp': 'ロリ', 'zh-cn': '萝莉' },
    208: { 'en-us': 'Puni', 'ja-jp': 'ぷに', 'zh-cn': '娃娃脸', 'zh-tw': '娃娃臉' },
    209: { 'en-us': 'Senior', 'ja-jp': '年上', 'zh-cn': '年上', 'zh-tw': '年上' },
    210: { 'en-us': 'Boy', 'ja-jp': '少年', 'zh-cn': '少年', 'zh-tw': '少年' },
    211: { 'en-us': 'Shota', 'ja-jp': 'ショタ', 'zh-cn': '正太', 'zh-tw': '正太' },
    212: { 'en-us': 'Younger Sister', 'ja-jp': '妹', 'zh-cn': '妹妹', 'zh-tw': '妹妹' },
    213: { 'en-us': 'Mother', 'ja-jp': '母親', 'zh-cn': '母亲', 'zh-tw': '母親' },
    214: { 'en-us': 'Younger Stepsister', 'ja-jp': '義妹', 'zh-cn': '义妹', 'zh-tw': '義妹/小姨子' },
    215: { 'en-us': 'Daughter', 'ja-jp': '娘', 'zh-cn': '女儿', 'zh-tw': '女兒' },
    216: { 'en-us': 'Stepmother', 'ja-jp': '義母', 'zh-cn': '义母', 'zh-tw': '岳母' },
    217: { 'en-us': 'Older Stepsister', 'ja-jp': '義姉', 'zh-cn': '义姐', 'zh-tw': '義姊/兄嫂' },
    218: { 'en-us': 'Mature Woman / MILF', 'ja-jp': '熟女', 'zh-cn': '熟女', 'zh-tw': '熟女' },
    219: { 'en-us': 'Married Woman', 'ja-jp': '人妻', 'zh-cn': '人妻', 'zh-tw': '人妻' },
    220: { 'en-us': 'Oneesan / Older Girl / Older Sister', 'ja-jp': 'お姉さん', 'zh-cn': '姐姐', 'zh-tw': '姊姊' },
    221: { 'en-us': 'Married Person', 'ja-jp': '既婚者', 'zh-cn': '已婚者', 'zh-tw': '已婚' },
    222: { 'en-us': 'Childhood Friend', 'ja-jp': '幼なじみ', 'zh-cn': '青梅竹马', 'zh-tw': '青梅竹馬' },
    223: { 'en-us': 'Twins', 'ja-jp': '双子', 'zh-cn': '双胞胎', 'zh-tw': '雙胞胎' },
    224: { 'en-us': 'School Nurse', 'ja-jp': '保健医', 'zh-cn': '保健医/校医', 'zh-tw': '校醫' },
    225: { 'en-us': 'Female Doctor', 'ja-jp': '女医', 'zh-cn': '女医生', 'zh-tw': '女醫' },
    226: { 'en-us': 'Female Teacher', 'ja-jp': '女教師', 'zh-cn': '女教师', 'zh-tw': '女老師' },
    227: { 'en-us': 'Teacher', 'ja-jp': '教師', 'zh-cn': '教师', 'zh-tw': '老師' },
    229: { 'ja-jp': '先輩' },
    230: { 'en-us': 'Salaried Worker', 'ja-jp': 'サラリーマン', 'zh-cn': '白领/上班族', 'zh-tw': '上班族' },
    231: { 'en-us': 'Host', 'ja-jp': 'ホスト', 'zh-cn': '牛郎', 'zh-tw': '牛郎' },
    232: { 'en-us': 'Office Lady', 'ja-jp': 'OL', 'zh-cn': 'OL', 'zh-tw': 'OL' },
    233: { 'en-us': 'Warrior', 'ja-jp': '戦士', 'zh-cn': '战士', 'zh-tw': '戰士' },
    234: { 'en-us': 'Queen / Princess', 'ja-jp': '女王様/お姫様', 'zh-cn': '女王/公主', 'zh-tw': '女王/公主' },
    235: { 'en-us': 'Elf / Fairy', 'ja-jp': 'エルフ/妖精', 'zh-cn': '精灵/妖精', 'zh-tw': '精靈/妖精' },
    237: { 'en-us': 'Angel / Demon', 'ja-jp': '天使/悪魔', 'zh-cn': '天使/恶魔', 'zh-tw': '天使/惡魔' },
    238: { 'ja-jp': '同性愛者' },
    239: { 'en-us': 'Ghost', 'ja-jp': '幽霊', 'zh-cn': '幽灵', 'zh-tw': '幽靈' },
    240: { 'en-us': 'Magical Girl', 'ja-jp': '魔法少女', 'zh-cn': '魔法少女', 'zh-tw': '魔法少女' },
    241: { 'en-us': 'Magician / Witch', 'ja-jp': '魔法使い/魔女', 'zh-cn': '魔法师/魔女', 'zh-tw': '魔法師/魔女' },
    242: { 'en-us': 'Upper-class Girl', 'ja-jp': 'お嬢様', 'zh-cn': '大小姐', 'zh-tw': '大小姐' },
    243: { 'en-us': 'Youkai', 'ja-jp': '妖怪', 'zh-cn': '妖怪', 'zh-tw': '妖怪' },
    244: { 'en-us': 'Shemale', 'ja-jp': 'ニューハーフ', 'zh-cn': '人妖/双性人', 'zh-tw': '第三性' },
    245: { 'en-us': 'Sex Change / Transsexual', 'ja-jp': '性転換(TS)', 'zh-cn': '性转换（TS）', 'zh-tw': '性轉（TS）' },
    246: { 'en-us': 'Natural Airhead', 'ja-jp': '天然', 'zh-cn': '天然呆', 'zh-tw': '天然呆' },
    247: { 'ja-jp': '電波' },
    248: { 'en-us': 'Intellectual', 'ja-jp': 'インテリ', 'zh-cn': '知识分子', 'zh-tw': '知識分子' },
    249: { 'en-us': 'Personification', 'ja-jp': '擬人化', 'zh-cn': '拟人化', 'zh-tw': '擬人化' },
    250: { 'en-us': 'Feminization', 'ja-jp': '女体化', 'zh-cn': '女体化', 'zh-tw': '女體化' },
    251: { 'en-us': 'Kemo / Animalization / Transfur', 'ja-jp': 'けもの/獣化', 'zh-cn': '野兽/兽化', 'zh-tw': '野獸/獸化' },
    254: { 'en-us': 'Robot / Android', 'ja-jp': 'ロボット/アンドロイド', 'zh-cn': '机器人/人工智能', 'zh-tw': '機器人/人造人' },
    255: { 'en-us': 'Glasses', 'ja-jp': 'メガネ', 'zh-cn': '眼镜', 'zh-tw': '眼鏡' },
    256: { 'en-us': 'Collar / Chain / Restraints', 'ja-jp': '首輪/鎖/拘束具', 'zh-cn': '项圈/锁链/拘束道具', 'zh-tw': '項圈/鍊子/束縛道具' },
    257: { 'en-us': 'Foreign Objects', 'ja-jp': '道具/異物', 'zh-cn': '道具/异物', 'zh-tw': '道具/異物' },
    258: { 'en-us': 'Socks', 'ja-jp': '靴下', 'zh-cn': '袜子', 'zh-tw': '襪子' },
    260: { 'en-us': 'Piercings / Accessories', 'ja-jp': 'ピアス/装飾品', 'zh-cn': '耳环/装饰品', 'zh-tw': '耳環/裝飾品' },
    262: { 'en-us': 'Whip / Rope / Candle', 'ja-jp': 'ムチ/縄/蝋燭', 'zh-cn': '鞭子/绳子/蜡烛', 'zh-tw': '鞭子/繩子/蠟燭' },
    263: { 'en-us': 'Toys', 'ja-jp': 'おもちゃ', 'zh-cn': '玩具', 'zh-tw': '玩具' },
    265: { 'en-us': 'Drugs', 'ja-jp': '薬物', 'zh-cn': '药物', 'zh-tw': '藥物' },
    266: { 'en-us': 'Lotion', 'ja-jp': 'ローション', 'zh-cn': '润滑液', 'zh-tw': '潤滑液' },
    268: { 'en-us': 'Sisters', 'ja-jp': '姉妹', 'zh-cn': '姐妹', 'zh-tw': '姊妹' },
    269: { 'en-us': 'Transforming Girl', 'ja-jp': '変身ヒロイン', 'zh-cn': '变身女主', 'zh-tw': '變身女主角' },
    270: { 'en-us': 'Gekokujo (the lower rules the higher)', 'ja-jp': '下克上', 'zh-cn': '下克上', 'zh-tw': '下克上' },
    271: { 'en-us': 'Reversible', 'ja-jp': 'リバ', 'zh-cn': '攻受互换' },
    272: { 'en-us': 'Crime / Gangster', 'ja-jp': 'ヤクザ/裏社会', 'zh-cn': '黑社会/里社会', 'zh-tw': '流氓/黑社會' },
    274: { 'en-us': 'Older Brother', 'ja-jp': '兄', 'zh-cn': '哥哥', 'zh-tw': '哥哥' },
    275: { 'en-us': 'Younger Brother', 'ja-jp': '弟', 'zh-cn': '弟弟', 'zh-tw': '弟弟' },
    276: { 'en-us': 'Father', 'ja-jp': '父', 'zh-cn': '父亲', 'zh-tw': '父親' },
    278: { 'en-us': 'Diligent (Submissive)', 'ja-jp': '健気受け', 'zh-cn': '健气受', 'zh-tw': '健氣受' },
    279: { 'en-us': 'Younger (Dominant)', 'ja-jp': '年下攻め', 'zh-cn': '年下攻', 'zh-tw': '年下攻' },
    281: { 'en-us': 'Classmate / Colleague', 'ja-jp': '同級生/同僚', 'zh-cn': '同学/同事', 'zh-tw': '同學/同事' },
    282: { 'en-us': 'Strong Willed (Submissive)', 'ja-jp': '強気受け', 'zh-cn': '强气受', 'zh-tw': '強氣受' },
    283: { 'en-us': 'Lordly Manner (Dominant)', 'ja-jp': '俺様攻め', 'zh-cn': '帝王攻', 'zh-tw': '帝王攻' },
    284: { 'en-us': 'Police / Detective', 'ja-jp': '警察/刑事', 'zh-cn': '警察/刑警', 'zh-tw': '警察/刑警' },
    285: { 'en-us': 'Junior / Senior (at work, school, etc)', 'ja-jp': '先輩/後輩', 'zh-cn': '前辈/后辈', 'zh-tw': '前輩/後輩' },
    286: { 'en-us': 'Mischievous (Submissive)', 'ja-jp': 'やんちゃ受け', 'zh-cn': '调皮受', 'zh-tw': '調皮受' },
    287: { 'en-us': 'Weak Willed (Dominant)', 'ja-jp': 'ヘタレ攻め', 'zh-cn': '无能攻', 'zh-tw': '無能攻' },
    288: { 'en-us': 'Master and Servant', 'ja-jp': '主従', 'zh-cn': '主从', 'zh-tw': '主奴' },
    289: { 'en-us': 'Seductive (Submissive)', 'ja-jp': '誘い受け', 'zh-cn': '诱受', 'zh-tw': '誘受' },
    290: { 'en-us': 'Cool Attitude (Dominant)', 'ja-jp': 'クール攻め', 'zh-cn': '高冷攻', 'zh-tw': '高冷攻' },
    291: { 'en-us': 'Middle Aged (Submissive)', 'ja-jp': 'オヤジ受け', 'zh-cn': '大叔受', 'zh-tw': '大叔受' },
    292: { 'en-us': 'Cool Attitude (Submissive)', 'ja-jp': 'クール受け', 'zh-cn': '冷淡受', 'zh-tw': '冷淡受' },
    293: { 'en-us': 'Butler', 'ja-jp': '執事', 'zh-cn': '管家/执事', 'zh-tw': '管家/執事' },
    295: { 'en-us': 'Softcore Eroticism', 'ja-jp': 'ソフトエッチ', 'zh-cn': '轻度H', 'zh-tw': '輕度H' },
    296: { 'en-us': 'Serial Product', 'ja-jp': 'シリーズもの', 'zh-cn': '系列作品' },
    298: { 'en-us': 'Mystery', 'ja-jp': 'ミステリー', 'zh-cn': '推理', 'zh-tw': '推理' },
    299: { 'en-us': 'Diaper', 'ja-jp': 'おむつ', 'zh-cn': '尿布/尿不湿', 'zh-tw': '尿布' },
    300: { 'en-us': 'Vore', 'ja-jp': '丸呑み', 'zh-cn': '丸吞', 'zh-tw': '丸吞' },
    301: { 'en-us': 'Train', 'ja-jp': '電車', 'zh-cn': '电车', 'zh-tw': '電車' },
    302: { 'en-us': 'Cuckoldry (Netori)', 'ja-jp': '寝取り', 'zh-cn': '寝取', 'zh-tw': '寢取' },
    303: { 'en-us': 'Otoko no ko', 'ja-jp': '男の娘', 'zh-cn': '伪娘', 'zh-tw': '偽娘' },
    304: { 'ja-jp': 'おやじ' },
    306: { 'ja-jp': 'あまあま' },
    307: { 'ja-jp': '無理矢理' },
    308: { 'en-us': 'Cooking / Gourmet', 'ja-jp': '料理/グルメ', 'zh-cn': '料理/美食' },
    309: { 'en-us': 'Anthology', 'ja-jp': 'アンソロジー', 'zh-cn': '作品集', 'zh-tw': '作品集' },
    310: { 'en-us': 'Critical Essay', 'ja-jp': '評論', 'zh-cn': '评论' },
    311: { 'en-us': 'Touch / Feel', 'ja-jp': 'おさわり', 'zh-cn': '触摸', 'zh-tw': '觸摸' },
    312: { 'en-us': 'Clothes Changing / Dress up', 'ja-jp': 'きせかえ', 'zh-cn': '换装', 'zh-tw': '換裝' },
    313: { 'en-us': 'Ryona / Brutal', 'ja-jp': 'リョナ', 'zh-cn': '凌虐', 'zh-tw': '受虐' },
    314: { 'en-us': 'Hypnotic Voice', 'ja-jp': '催眠音声', 'zh-cn': '催眠音声' },
    315: { 'en-us': 'Real Elder Sister', 'ja-jp': '実姉', 'zh-cn': '亲姐', 'zh-tw': '親姊姊' },
    316: { 'en-us': 'Yandere', 'ja-jp': 'ヤンデレ', 'zh-cn': '病娇', 'zh-tw': '病嬌' },
    317: { 'en-us': 'Monster girls', 'ja-jp': '人外娘/モンスター娘', 'zh-cn': '魔物娘', 'zh-tw': '魔物娘' },
    318: { 'en-us': 'Company President', 'ja-jp': '社長', 'zh-cn': '社长', 'zh-tw': '公司老闆' },
    319: { 'en-us': 'Doctor', 'ja-jp': '医者', 'zh-cn': '医生', 'zh-tw': '醫生' },
    321: { 'en-us': 'Tanned Skin / Suntan', 'ja-jp': '褐色/日焼け', 'zh-cn': '褐色肌肤/黝黑', 'zh-tw': '褐膚色/黝黑' },
    322: { 'en-us': 'Phimosis', 'ja-jp': '包茎', 'zh-cn': '包茎', 'zh-tw': '包莖' },
    323: { 'en-us': 'Ahegao / Gapeface', 'ja-jp': 'アヘ顔', 'zh-cn': '啊嘿颜', 'zh-tw': '阿黑顏' },
    324: { 'en-us': 'Interspecies Sex', 'ja-jp': '異種姦', 'zh-cn': '异种奸' },
    325: { 'en-us': 'Corrupted Morals', 'ja-jp': '悪堕ち', 'zh-cn': '恶堕', 'zh-tw': '惡墮' },
    326: { 'en-us': 'Brainwashing', 'ja-jp': '洗脳', 'zh-cn': '洗脑' },
    399: { 'en-us': 'Seinen', 'ja-jp': '青年', 'zh-cn': '青年' },
    400: { 'en-us': 'Student', 'ja-jp': '学生', 'zh-cn': '学生', 'zh-tw': '學生' },
    401: { 'en-us': 'Blue-collar Worker', 'ja-jp': 'ガテン系', 'zh-cn': '工人', 'zh-tw': '工人' },
    405: { 'en-us': 'Wrestler / Fighter', 'ja-jp': 'レスラー/格闘家', 'zh-cn': '摔角手/格斗家', 'zh-tw': '摔角手/格鬥家' },
    409: { 'en-us': 'Entertainer / Idol / Model', 'ja-jp': '芸能人/アイドル/モデル', 'zh-cn': '艺人/偶像/模特', 'zh-tw': '藝人/偶像/模特兒' },
    411: { 'en-us': 'Jock / Athlete / Sports', 'ja-jp': '体育会系/スポーツ選手', 'zh-cn': '体育会系/体育选手', 'zh-tw': '體育社團系/運動選手' },
    412: { 'en-us': 'Foreigner', 'ja-jp': '外国人', 'zh-cn': '外国人', 'zh-tw': '外國人' },
    413: { 'en-us': 'Playboy', 'ja-jp': 'ヤリチン/プレイボーイ', 'zh-cn': '花花公子', 'zh-tw': '花花公子' },
    414: { 'en-us': 'Zombie', 'ja-jp': 'ゾンビ', 'zh-cn': '僵尸/丧尸', 'zh-tw': '殭屍' },
    415: { 'en-us': 'Gal', 'ja-jp': 'ギャル', 'zh-cn': '辣妹', 'zh-tw': '辣妹' },
    416: { 'en-us': 'Bitch / Slut', 'ja-jp': 'ビッチ', 'zh-cn': '婊子', 'zh-tw': '婊子' },
    419: { 'en-us': 'Delinquent / Hoodlum', 'ja-jp': '不良/ヤンキー', 'zh-cn': '不良/混混', 'zh-tw': '不良少年' },
    420: { 'en-us': 'Reverse Harem', 'ja-jp': '逆ハーレム', 'zh-cn': '逆后宫' },
    422: { 'en-us': 'Egocentric', 'ja-jp': '俺様', 'zh-cn': '高傲男' },
    423: { 'en-us': 'Uncle / Stepfather', 'ja-jp': '叔父/義父', 'zh-cn': '叔父/义父', 'zh-tw': '叔父/岳父' },
    424: { 'en-us': 'Boss', 'ja-jp': '上司', 'zh-cn': '上司', 'zh-tw': '上司' },
    425: { 'en-us': 'Arab', 'ja-jp': 'アラブ', 'zh-cn': '阿拉伯' },
    426: { 'en-us': 'Male Pregnancy / Delivery', 'ja-jp': '男子妊娠/出産', 'zh-cn': '男子怀孕/分娩' },
    427: { 'en-us': 'Prince / Royalty', 'ja-jp': '王子様/王子系', 'zh-cn': '王子殿下/王子系' },
    431: { 'en-us': 'Dot / Pixel', 'ja-jp': 'ドット', 'zh-cn': '像素', 'zh-tw': '點陣圖' },
    432: { 'en-us': 'Female Protagonist', 'ja-jp': '女主人公', 'zh-cn': '女主人公', 'zh-tw': '女主角' },
    433: { 'en-us': 'No Reverse', 'ja-jp': '逆転無し', 'zh-cn': '无逆转', 'zh-tw': '無逆轉' },
    434: { 'ja-jp': '男無' },
    436: { 'ja-jp': '出会い' },
    437: { 'en-us': 'First Experience', 'ja-jp': '初体験', 'zh-cn': '初体验', 'zh-tw': '初體驗' },
    438: { 'en-us': 'Cohabitation', 'ja-jp': '同棲', 'zh-cn': '同居', 'zh-tw': '同居' },
    440: { 'en-us': 'Cheating / Adultery', 'ja-jp': '浮気', 'zh-cn': '出轨', 'zh-tw': '出軌/外遇' },
    441: { 'en-us': 'Non-fiction / Real Story', 'ja-jp': 'ノンフィクション/体験談', 'zh-cn': '记录片/体验谈', 'zh-tw': '真實體驗/非虛構' },
    442: { 'en-us': 'Ear Cleaning', 'ja-jp': '耳かき', 'zh-cn': '掏耳', 'zh-tw': '掏耳朵' },
    443: { 'en-us': 'Possession', 'ja-jp': '憑依', 'zh-cn': '附身', 'zh-tw': '附身' },
    444: { 'en-us': 'Time Stopping', 'ja-jp': '時間停止', 'zh-cn': '时间停止', 'zh-tw': '時間停止' },
    445: { 'en-us': 'Petrifaction', 'ja-jp': '石化', 'zh-cn': '石化', 'zh-tw': '石化' },
    446: { 'en-us': 'Prostitution / Paid Dating', 'ja-jp': '売春/援交', 'zh-cn': '卖春/援交', 'zh-tw': '賣春/援交' },
    447: { 'en-us': 'Sex Industry / Soapland', 'ja-jp': '風俗/ソープ', 'zh-cn': '风俗/泡泡店', 'zh-tw': '風俗店/泡泡浴' },
    448: { 'en-us': 'Coquettish / Seduction', 'ja-jp': '色仕掛け', 'zh-cn': '色诱', 'zh-tw': '色誘' },
    450: { 'en-us': 'Shonen Manga', 'ja-jp': '少年コミック', 'zh-cn': '少年漫画' },
    451: { 'en-us': 'Shojo Manga', 'ja-jp': '少女コミック', 'zh-cn': '少女漫画' },
    452: { 'en-us': 'Seinen Manga', 'ja-jp': '青年コミック', 'zh-cn': '青年漫画' },
    453: { 'en-us': 'Josei Manga', 'ja-jp': '女性コミック', 'zh-cn': '女性漫画' },
    454: { 'en-us': 'Animal / Pet', 'ja-jp': '動物/ペット', 'zh-cn': '动物/宠物' },
    455: { 'en-us': 'Love Comedy / Romcom', 'ja-jp': 'ラブコメ', 'zh-cn': '爱情喜剧', 'zh-tw': '愛情喜劇' },
    461: { 'en-us': 'Urethra', 'ja-jp': '尿道', 'zh-cn': '尿道', 'zh-tw': '尿道' },
    462: { 'en-us': 'Heterosexual / Nonke', 'ja-jp': 'ノンケ', 'zh-cn': '直男/直女' },
    463: { 'en-us': 'Bisexual', 'ja-jp': 'バイ', 'zh-cn': '双性恋', 'zh-tw': '雙性戀' },
    464: { 'en-us': 'Spanking', 'ja-jp': 'スパンキング', 'zh-cn': '拍打', 'zh-tw': '拍打' },
    465: { 'en-us': 'Mob Sex', 'ja-jp': 'モブ姦', 'zh-cn': '路人奸' },
    472: { 'en-us': 'Stout and Sturdy', 'ja-jp': 'ガチムチ', 'zh-cn': '健壮' },
    473: { 'en-us': 'Chubby / Fat', 'ja-jp': '太め/デブ', 'zh-cn': '稍胖', 'zh-tw': '稍胖' },
    478: { 'en-us': 'Short Hair (Male)', 'ja-jp': '短髪', 'zh-cn': '短发' },
    484: { 'en-us': 'Gut Punch', 'ja-jp': '腹パン', 'zh-cn': '腹击', 'zh-tw': '腹擊' },
    486: { 'en-us': 'Widow', 'ja-jp': '未亡人', 'zh-cn': '寡妇', 'zh-tw': '寡婦' },
    487: { 'en-us': 'Irrumatio', 'ja-jp': 'イラマチオ', 'zh-cn': '深喉', 'zh-tw': '深喉嚨' },
    488: { 'en-us': 'Oral Cumshot', 'ja-jp': '口内射精', 'zh-cn': '口爆', 'zh-tw': '口爆' },
    489: { 'en-us': 'Cum Swallowing', 'ja-jp': 'ごっくん/食ザー', 'zh-cn': '吞精', 'zh-tw': '吞精' },
    490: { 'en-us': 'Insect Sex', 'ja-jp': '蟲姦', 'zh-cn': '虫奸' },
    491: { 'ja-jp': '女性向' },
    493: { 'en-us': 'Omegaverse', 'ja-jp': 'オメガバース', 'zh-cn': 'ABO世界观' },
    494: { 'en-us': 'Romance', 'ja-jp': 'ロマンス', 'zh-cn': '浪漫' },
    495: { 'en-us': 'Sleep Sex', 'ja-jp': '睡眠姦', 'zh-cn': '睡眠奸' },
    496: { 'en-us': 'Binaural', 'ja-jp': 'バイノーラル/ダミヘ', 'zh-cn': '双声道立体声/人头麦', 'zh-tw': '環繞音' },
    497: { 'en-us': 'ASMR', 'ja-jp': 'ASMR', 'zh-cn': 'ASMR', 'zh-tw': 'ASMR' },
    499: { 'en-us': 'Cunnilingus', 'ja-jp': 'クンニ', 'zh-cn': '舔阴' },
    500: { 'en-us': 'Ear Licking', 'ja-jp': '耳舐め', 'zh-cn': '舔耳', 'zh-tw': '舔耳' },
    501: { 'en-us': 'Squirting / Gushing', 'ja-jp': '潮吹き', 'zh-cn': '潮吹', 'zh-tw': '潮吹' },
    502: { 'en-us': 'Male Protagonist', 'ja-jp': '男主人公', 'zh-cn': '男主人公', 'zh-tw': '男主角' },
    503: { 'en-us': 'Whispering', 'ja-jp': 'ささやき', 'zh-cn': '低语', 'zh-tw': '低語' },
    504: { 'en-us': 'Elder Girl x Younger Boy', 'ja-jp': 'おねショタ', 'zh-cn': '姐姐正太', 'zh-tw': '姊姊正太' },
    505: { 'en-us': 'Kunoichi (Ninja Girl)', 'ja-jp': 'くノ一', 'zh-cn': '女忍者', 'zh-tw': '女忍者' },
    506: { 'en-us': 'Succubus / Incubus', 'ja-jp': 'サキュバス/淫魔', 'zh-cn': '魅魔/淫魔', 'zh-tw': '魅魔/淫魔' },
    507: { 'en-us': 'Technical Book', 'ja-jp': '技術書', 'zh-cn': '技术书', 'zh-tw': '技術書' },
    508: { 'en-us': 'TRPG', 'ja-jp': 'TRPG', 'zh-cn': 'TRPG（桌游）', 'zh-tw': 'TRPG（桌面遊戯）' },
    509: { 'en-us': '3D Works', 'ja-jp': '3D作品', 'zh-cn': '3D作品', 'zh-tw': '3D作品' },
    510: { 'en-us': 'RPG Maker', 'ja-jp': 'ツクール', 'zh-cn': '制作大师', 'zh-tw': '製作大師' },
    512: { 'en-us': 'Touhou Project', 'ja-jp': '東方Project', 'zh-cn': '东方Project', 'zh-tw': '東方Project' },
    513: { 'en-us': 'Vtuber', 'ja-jp': 'VTuber', 'zh-cn': 'VTuber', 'zh-tw': 'VTuber' },
    514: { 'en-us': 'Guided Masturbation', 'ja-jp': 'オナサポ', 'zh-cn': '自慰帮手', 'zh-tw': '自慰幫手' },
    515: { 'en-us': 'Compilation', 'ja-jp': '総集編', 'zh-cn': '总集篇', 'zh-tw': '總集篇' },
    516: { 'en-us': 'TRPG Scenario', 'ja-jp': 'TRPGシナリオ', 'zh-cn': '跑团剧本', 'zh-tw': '跑團劇本' },
    517: { 'en-us': 'TRPG Session Recap', 'ja-jp': 'TRPGリプレイ集', 'zh-cn': '跑团回放合集', 'zh-tw': '跑團回放合集' },
    518: { 'en-us': 'TRPG Rulebook', 'ja-jp': 'TRPGルールブック', 'zh-cn': '跑团规则书', 'zh-tw': '跑團規則書' },
    519: { 'en-us': 'Isekai', 'ja-jp': '異世界転生', 'zh-cn': '异世界转生' },
    520: { 'en-us': 'Villainess', 'ja-jp': '悪役令嬢', 'zh-cn': '反派千金' },
    521: { 'en-us': 'Clingy (Dominant)', 'ja-jp': '執着攻め', 'zh-cn': '执着攻' },
    522: { 'en-us': 'Fem-corruption', 'ja-jp': 'メス堕ち', 'zh-cn': '雌堕' },
    523: { 'en-us': 'Nipple Teasing', 'ja-jp': '乳首責め', 'zh-cn': '乳头刺激', 'zh-tw': '乳頭刺激' },
    524: { 'en-us': 'Vulgar Moans', 'ja-jp': 'オホ声', 'zh-cn': '啊哦淫叫', 'zh-tw': '哦齁淫叫' },
    525: { 'en-us': 'Mesugaki', 'ja-jp': 'メスガキ', 'zh-cn': '雌小鬼' },
    526: { 'en-us': 'Pleasure Corruption', 'ja-jp': '快楽堕ち', 'zh-cn': '沉迷快乐', 'zh-tw': '沉淪快樂' },
    527: { 'en-us': 'Clit Teasing', 'ja-jp': 'クリ責め', 'zh-cn': '阴蒂刺激', 'zh-tw': '陰蒂刺激' },
    528: { 'en-us': 'No Penetrative Sex', 'ja-jp': '本番なし', 'zh-cn': '无本番', 'zh-tw': '無本番' },
    529: { 'en-us': 'Cuckoldry (Netorase)', 'ja-jp': '寝取らせ', 'zh-cn': 'NTR', 'zh-tw': 'NTR' },
    530: { 'en-us': 'Reverse Cuckoldry', 'ja-jp': '逆NTR', 'zh-cn': '逆NTR', 'zh-tw': '逆NTR' },
    531: { 'en-us': 'Lolibaba', 'ja-jp': 'ロリババア', 'zh-cn': '萝莉老太婆' },
    532: { 'en-us': 'Reverse Anal', 'ja-jp': '逆アナル', 'zh-cn': '逆肛交', 'zh-tw': '逆肛交' },
    533: { 'en-us': 'Battle Fuck', 'ja-jp': '戦闘エロ', 'zh-cn': '战斗H', 'zh-tw': '戰鬥H' },
    534: { 'en-us': 'Younger Boy x Elder Girl', 'ja-jp': 'ショタおね', 'zh-cn': '正太控女', 'zh-tw': '正太控女' },
    536: { 'en-us': 'Femdom', 'ja-jp': '女性優位', 'zh-cn': '女性主导' },
    537: { 'en-us': 'Pectorals / Man Boobs', 'ja-jp': '雄っぱい', 'zh-cn': '男性胸部' },
    538: { 'en-us': 'Mommie', 'ja-jp': 'ママ', 'zh-cn': '妈妈' },
    539: { 'en-us': 'Body Size Disparity', 'ja-jp': '体格差', 'zh-cn': '体型差' },
    540: { 'en-us': 'Babyplay', 'ja-jp': '赤ちゃんプレイ', 'zh-cn': '婴儿PLAY' },
    541: { 'en-us': 'Beastkin', 'ja-jp': '獣人', 'zh-cn': '兽人' },
    573: { 'ja-jp': '儿童绘本' },
    580: { 'ja-jp': '铁路' },
    583: { 'ja-jp': '占卜' },
    588: { 'ja-jp': '素材集' },
    612: { 'ja-jp': '自我启发' },
    634: { 'ja-jp': '有声书' },
    636: { 'en-us': 'Co-sleeping', 'ja-jp': '添い寝', 'zh-cn': '陪睡', 'zh-tw': '陪睡' },
    637: { 'en-us': 'Kissing', 'ja-jp': 'キス', 'zh-cn': '亲吻', 'zh-tw': '親吻' },
    638: { 'en-us': 'Ear Blowing', 'ja-jp': '耳ふー', 'zh-cn': '吹耳朵"', 'zh-tw': '吹耳朵' },
    639: { 'en-us': 'Sleep Induction', 'ja-jp': '睡眠導入', 'zh-cn': '助眠', 'zh-tw': '助眠' },
    640: { 'en-us': 'RPGBakin', 'ja-jp': 'RPGBakin', 'zh-cn': 'RPGBakin', 'zh-tw': 'RPGBakin' },
    641: { 'en-us': 'Burping', 'ja-jp': 'ゲップ', 'zh-cn': '打嗝', 'zh-tw': '打嗝' },
    642: { 'en-us': 'Sensory Deprivation', 'ja-jp': '感覚遮断', 'zh-cn': '感官屏蔽', 'zh-tw': '感官屏蔽' },
    643: { 'en-us': 'Personality Excretion', 'ja-jp': '人格排泄', 'zh-cn': '人格排泄', 'zh-tw': '人格排洩' },
    644: { 'en-us': 'BSS / Thwarted Love', 'ja-jp': 'BSS', 'zh-cn': 'BSS/暗恋被抢', 'zh-tw': 'BSS/暗戀被搶' },
    645: { 'en-us': 'Partner Swapping', 'ja-jp': 'スワッピング', 'zh-cn': '换偶', 'zh-tw': '換偶' },
    646: { 'en-us': 'Glans Stimulation', 'ja-jp': '亀頭責め', 'zh-cn': '龟头刺激', 'zh-tw': '龜頭刺激' },
    647: { 'en-us': '膨乳', 'ja-jp': '膨乳', 'zh-cn': '膨乳', 'zh-tw': '膨乳' },
    648: { 'en-us': 'Womb Tattoo / Lust Crest', 'ja-jp': '淫紋', 'zh-cn': '淫纹', 'zh-tw': '淫紋' },
    649: { 'en-us': 'Moan Imitation', 'ja-jp': '喘ぎ真似', 'zh-cn': '模仿娇喘' },
    650: { 'en-us': 'Real Elder Brother', 'ja-jp': '実兄', 'zh-cn': '亲哥哥' },
    651: { 'en-us': 'Formal Speech', 'ja-jp': '敬語', 'zh-cn': '敬语' },
    652: { 'en-us': 'Infatuation', 'ja-jp': '溺愛', 'zh-cn': '溺爱' },
    653: { 'en-us': 'Mutual Unrequited Love', 'ja-jp': '両片思い', 'zh-cn': '双向暗恋' },
    654: { 'en-us': 'Prone Bone', 'ja-jp': '寝バック', 'zh-cn': '平趴后入' },
    656: { 'en-us': 'Femme Man', 'ja-jp': 'メスお兄さん', 'zh-cn': '雌哥哥' },
    658: { 'en-us': 'Power Bottom', 'ja-jp': '受け優位', 'zh-cn': '受方主导' },
    659: { 'en-us': 'Massage', 'ja-jp': 'マッサージ', 'zh-cn': '按摩', 'zh-tw': '按摩' },
    660: { 'en-us': 'Languid', 'ja-jp': 'ダウナー', 'zh-cn': '阴郁系', 'zh-tw': '陰鬱系' },
    661: { 'en-us': 'Altered Sense of Normal', 'ja-jp': '常識改変', 'zh-cn': '常识改变', 'zh-tw': '常識改變' },
    662: { 'en-us': 'Non-human', 'ja-jp': '人外', 'zh-cn': '人外' },
    663: { 'en-us': 'Same-Sex Physical Contact (Male)', 'ja-jp': '男性間接触', 'zh-cn': '男性间接触', 'zh-tw': '男性間接触' },
    664: { 'en-us': '女性間接触', 'ja-jp': '女性間接触', 'zh-cn': '女性間接触', 'zh-tw': '女性間接触' },
    10000: { 'ja-jp': 'AI' },
    10001: { 'ja-jp': '乙女向' },
};
